blank_issues_enabled: false
contact_links:
  - name: Security Policy
    url: https://github.com/danyzly/builderbadge-multichain/security/policy
    about: Please report security vulnerabilities here.
  - name: Discussions
    url: https://github.com/danyzly/builderbadge-multichain/discussions
    about: For general questions or open-ended conversations.
